steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "us-east1-docker.pkg.dev/images-across-6363/scraper-api/scraper-api", "."]
options:
  machineType: "E2_HIGHCPU_8"
timeout: 3600s
images: ["us-east1-docker.pkg.dev/images-across-6363/scraper-api/scraper-api"]
tags: ["stage"]
