version: "3.7"

services:
  backend:
    container_name: scraper-api-backend-e2e
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - backend-e2e-node-modules:/usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    command: ["/bin/sh", "./docker/e2e.command.sh"]
    env_file:
      - .env.test
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgres
      - DB_PORT=5432
    tty: true
    depends_on:
      - postgres
      - redis
  postgres:
    container_name: scraper-api-postgres-e2e
    image: postgres:12.2
    environment:
      TZ: GMT
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - scraper-api-pgdata-e2e:/var/lib/postgresql/data
  redis:
    container_name: scraper-api-redis-e2e
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - scraper-api-redis-volume-e2e:/data
volumes:
  backend-e2e-node-modules:
  scraper-api-pgdata-e2e:
  scraper-api-redis-volume-e2e:
