name: Lint, build and test

on:
  push:
    branches:
      - stage
      - master
  pull_request:

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: yarn lint
      - run: yarn build
  e2e-tests:
    runs-on: ubuntu-latest
    env:
      PORT: 3001
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_USERNAME: scraperapi
      DB_PASSWORD: scraperapipassword
      DB_DATABASE_NAME: scraperapi
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
      WEB3_NODE_URL_1: https://mainnet.infura.io/v3/
      WEB3_NODE_URL_10: https://optimism-mainnet.infura.io/v3/
      WEB3_NODE_URL_288: https://boba-mainnet.gateway.pokt.network/v1/lb/
      WEB3_NODE_URL_42161: https://arbitrum-mainnet.infura.io/v3/
      WEB3_NODE_URL_137: https://polygon-mainnet.infura.io/v3/
      REFERRAL_DELIMITER_START_TIMESTAMP: 1657290720
      ENABLE_SPOKE_POOLS_EVENTS_PROCESSING: false
      ENABLE_REFERRALS_MATERIALIZED_VIEW_REFRESH: false
      STICKY_REFERRAL_ADDRESSES_MECHANISM: queue
      DISABLE_CRONS: true
      JWT_SECRET: secret
      DISCORD_CLIENT_ID: clientId
      DISCORD_CLIENT_SECRET: clientSecret
      DISCORD_REDIRECT_URI: http://localhost
      DISTRIBUTOR_PROOFS_CACHE_SECONDS_DURATION: 0
      REFERRALS_SUMMARY_CACHE_SECONDS_DURATION: 0
      RUN_MODES: normal,test
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: cp .env.sample .env.test
      - name: Start postgres and redis
        run: docker-compose -f docker-compose.e2e.yml up -d postgres redis
      - name: Run migrations
        run: yarn db:migration:run
      - name: Run e2e tests
        run: yarn test:e2e --force-exit
